let news_datas = {
  data: [
    {
      id: "san-nha-sang-de-dang-voi-chinh-sach-khung-tra-gop-15-nam-khong-lo-lai-suat",
      img: "https://storage.googleapis.com/vinhomes-data-02/styles/images_263_x_146/public/2024_04/Screenshot 2024-04-09 at 10_1712633265.png?itok=pxhmH55Z",
      title:
        "Săn nhà sang dễ dàng với chính sách “khủng”: Trả góp 15 năm không lo lãi suất",
      content: `<h2 style="text-align: justify;color: rgb(47, 47, 47);background-color: rgb(255, 255, 255);font-size: 16px;">Ocean City, Th&agrave;nh phố điểm đến ph&iacute;a Đ&ocirc;ng H&agrave; Nội tự h&agrave;o được International Business Times (IBTimes)&nbsp;&ndash; Một trong những thời b&aacute;o kinh doanh lớn nhất tại Mỹ&nbsp;c&ugrave;ng nhiều thời b&aacute;o danh gi&aacute; tr&ecirc;n thế giới đ&aacute;nh gi&aacute; l&agrave; Nơi đ&aacute;ng sống bậc nhất h&agrave;nh tinh.</h2>
      <div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;">
          <p style="text-align: justify;color: rgb(34, 34, 34);font-size: 13px;"><span style="font-size: 12pt;"><span style="font-size: 11pt;"><span style="color: black;">Trải qua h&agrave;nh tr&igrave;nh hơn 5 năm h&igrave;nh th&agrave;nh &amp; ph&aacute;t triển, Ocean City đ&atilde; trở th&agrave;nh <strong><strong>điểm đến hấp dẫn cho c&aacute;c c&ocirc;ng d&acirc;n to&agrave;n cầu</strong></strong></span></span><strong><strong><span style="font-size: 11pt;"><span style="color: black;">&nbsp;sống kết nối, ho&agrave; m&igrave;nh v&agrave;o sự ph&aacute;t triển, đề cao gi&aacute; trị sức khoẻ, tinh thần v&agrave; cộng đồng</span></span></strong></strong><span style="font-size: 11pt;"><span style="color: black;">. Nơi đ&acirc;y hiện</span></span> <span style="font-size: 11pt;"><span style="color: black;">l&agrave; ng&ocirc;i nh&agrave; của hơn <strong><strong>60.000 cư d&acirc;n, gồm cả cư d&acirc;n Việt Nam v&agrave; quốc tế</strong></strong>. Trong đ&oacute;, <strong><strong>cộng đồng cư d&acirc;n H&agrave;n Quốc đang</strong></strong></span></span><strong><strong>&nbsp;</strong></strong><strong><strong><span style="font-size: 11pt;"><span style="color: black;">chiếm số lượng đ&ocirc;ng đảo nhất</span></span></strong></strong><strong><strong>&nbsp;</strong></strong><span style="font-size: 11pt;"><span style="color: black;">trong cộng đồng&nbsp;</span></span><span style="font-size: 11pt;"><span style="color: black;">cư</span></span><span style="font-size: 11pt;"><span style="color: black;">&nbsp;d&acirc;n quốc tế. Đ&oacute; l&agrave; t&iacute;n hiệu đ&aacute;ng mừng cho thấy Ocean City được cộng đồng cư d&acirc;n H&agrave;n Quốc tại Việt Nam đ&oacute;n nhận rất t&iacute;ch cực.</span></span></span></p>
          <p style="text-align: justify;color: rgb(34, 34, 34);font-size: 13px;">&nbsp;</p>
          <p style="text-align: justify;color: rgb(34, 34, 34);font-size: 13px;"><span style="font-size: 12pt;"><span style="font-size: 11pt;"><span style="color: black;">Đ&aacute;p lại sự tin y&ecirc;u của cộng đồng H&agrave;n Quốc, trong thời gian qua, Ocean City lu&ocirc;n <strong><strong>đầu tư mạnh mẽ v&agrave;o h&agrave;ng loạt c&aacute;c dịch vụ, tiện &iacute;ch cũng như ch&iacute;nh s&aacute;ch ưu đ&atilde;i d&agrave;nh ri&ecirc;ng cho cư d&acirc;n/kh&aacute;ch h&agrave;ng H&agrave;n Quốc</strong></strong> nhằm mục ti&ecirc;u thu h&uacute;t v&agrave; ph&aacute;t triển cộng đồng H&agrave;n Quốc tại Ocean City.</span></span></span></p>
          <p style="text-align: justify;color: rgb(34, 34, 34);font-size: 13px;"><img src="https://storage.googleapis.com/vinhomes-data-02/styles/images_160_x_120/public/2022_10/1303_Anh_1_1666754093.jpeg?itok=KisV6NIx" alt=""><br></p>
      </div>`,
    },
    {
      id: "doi-van-tu-thue-tro-thanh-chu-can-ho-hang-sang-nho-biet-tan-dung-goi-vay",
      img: "https://storage.googleapis.com/vinhomes-data-02/styles/images_263_x_146/public/2024_04/Screenshot 2024-04-09 at 10_1712632823.png?itok=ewsobWgC",
      title:
        "‘Đổi vận’ từ thuê trọ thành chủ căn hộ hạng sang nhờ biết tận dụng gói vay",
      content: `<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;"><strong><strong>Gi&aacute; thu&ecirc; nh&agrave; li&ecirc;n tục nhảy vọt</strong></strong></p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Căn hộ hiện l&agrave; loại h&igrave;nh nh&agrave; ở được người thu&ecirc; quan t&acirc;m nhiều nhất, chiếm tỷ lệ 43%. B&aacute;o c&aacute;o của Savills Việt Nam mới đ&acirc;y cho biết, <a href="https://vietnamnet.vn/gia-thue-nha-tag11917982688774359702.html" target="_blank" style="color: transparent;">gi&aacute; thu&ecirc; căn hộ</a> dịch vụ tại hai th&agrave;nh phố lớn đều đ&atilde; bật tăng mạnh. Tại TP.HCM, mức tăng dao động từ 3 - 8% t&ugrave;y ph&acirc;n kh&uacute;c. Tại H&agrave; Nội, gi&aacute; thu&ecirc; căn hộ đ&atilde; tăng từ 1 - 4%.&nbsp;</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">&Ocirc;ng Đinh Minh Tuấn, Gi&aacute;m đốc batdongsan.com.vn khu vực miền Nam ph&acirc;n t&iacute;ch, nhiều kh&aacute;ch h&agrave;ng chưa đủ tiền mua nh&agrave; n&ecirc;n sẽ đi thu&ecirc;, hoặc một số nh&oacute;m đi thu&ecirc; rồi cho thu&ecirc; lại để phục vụ du lịch trong nước. Mặt kh&aacute;c, &ocirc;ng Tuấn cho rằng, xu hướng đ&ocirc; thị h&oacute;a ng&agrave;y c&agrave;ng cao, d&acirc;n nhập cư v&agrave;o trung t&acirc;m nhiều dẫn đến nhu cầu thu&ecirc; chung cư, nh&agrave; trọ cũng gia tăng; thị trường cho thu&ecirc; v&igrave; thế trở n&ecirc;n s&ocirc;i động hơn thời điểm trước.</p>
<figure style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;">&nbsp;</figure>
<p style="text-align: center;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;"><img alt="vin 1.jpeg" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" srcset="https://static-images.vnncdn.net/files/publish/2024/3/13/vin-1-766.jpeg?width=0&s=CTKZuW6radd_sMy1seJxqQ" style="border: 0px;">&nbsp;</p>
<p style="text-align: center;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;"><em>Ng&agrave;y c&agrave;ng nhiều người trẻ linh hoạt tận dụng ưu đ&atilde;i thanh to&aacute;n tốt để mua nh&agrave;</em></p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Ở g&oacute;c nh&igrave;n kh&aacute;c, &ocirc;ng Neil MacGregor, Tổng Gi&aacute;m đốc Savills Việt Nam, cho biết nhu cầu căn hộ cho thu&ecirc; tăng mạnh mẽ c&ograve;n do sự gia tăng của đội ngũ chuy&ecirc;n gia nước ngo&agrave;i đến l&agrave;m việc tại c&aacute;c dự &aacute;n c&oacute; vốn FDI. Trong đ&oacute;, nguồn vốn FDI đổ về c&aacute;c khu c&ocirc;ng nghiệp, tập trung tại ph&iacute;a đ&ocirc;ng TP.HCM, ph&iacute;a đ&ocirc;ng v&agrave; t&acirc;y H&agrave; Nội, chiếm tỷ trọng &aacute;p đảo n&ecirc;n đ&acirc;y l&agrave; những &ldquo;điểm n&oacute;ng&rdquo; tăng mạnh gi&aacute; thu&ecirc; suốt thời gian qua.</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">C&ugrave;ng với đ&agrave; tăng trưởng vượt trội của gi&aacute; thu&ecirc;, đ&atilde; c&oacute; sự thay đổi lớn trong độ tuổi mua nh&agrave;. Theo batdongsan.com.vn, độ tuổi từ 22 - 39 hiện l&agrave; nh&oacute;m kh&aacute;ch c&oacute; nhu cầu mua nh&agrave; chủ lực. Trong đ&oacute;, gen Z (nh&oacute;m tuổi 22 - 26) bứt ph&aacute; cực mạnh khi lượng t&igrave;m mua tăng từ 13% (2021) l&ecirc;n gần 19% (2023). Mong muốn sớm sở hữu bất động sản, người trẻ c&oacute; xu hướng vay để mua nh&agrave; cao hơn những người thuộc thế hệ trước. Theo đ&oacute;, tỷ lệ người 22 - 29 tuổi lựa chọn vay mua nh&agrave; l&ecirc;n đến 75%, trong khi tỷ lệ n&agrave;y ở những người tr&ecirc;n 30 tuổi chỉ 68%.&nbsp;</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">&Ocirc;ng L&ecirc; Bảo Long - Gi&aacute;m đốc Chiến lược của batdongsan.com.vn, l&yacute; giải phần lớn người Việt hiện đang chi từ 10 - 30% thu nhập cho việc thu&ecirc; nh&agrave; h&agrave;ng th&aacute;ng. V&igrave; vậy, việc mặt bằng gi&aacute; thu&ecirc; tăng cao đ&atilde; th&uacute;c đẩy t&acirc;m l&yacute; chuyển khoản tiền thu&ecirc; th&agrave;nh mua nh&agrave; trả g&oacute;p. Song song với đ&oacute;, sự nở rộ của c&aacute;c m&ocirc; h&igrave;nh kinh doanh dịch vụ, dịch vụ cho thu&ecirc; lại&hellip; hướng đến tệp kh&aacute;ch h&agrave;ng cao cấp, chuy&ecirc;n gia nước ngo&agrave;i đ&atilde; th&uacute;c đẩy nh&oacute;m chủ sở hữu trẻ tuổi tăng cao.</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;"><strong><strong>Cuộc ho&aacute;n đổi th&ocirc;ng minh của người trẻ</strong></strong></p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Giữa bối cảnh n&agrave;y, việc Vinhomes tung ra giải ph&aacute;p đột ph&aacute; tr&ecirc;n thị trường được xem l&agrave; đ&oacute;n tr&uacute;ng nhu cầu của người trẻ cần mua nh&agrave; cũng như c&aacute;c nh&agrave; đầu tư trẻ tuổi đang bước ch&acirc;n v&agrave;o thị trường bất động sản đầy tiềm năng.</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Ph&aacute;t huy tối đa ưu điểm v&agrave; khắc phục ho&agrave;n to&agrave;n bất cập của phương thức mua nh&agrave; trả g&oacute;p, ch&iacute;nh s&aacute;ch của Vinhomes được nhiều người trẻ v&iacute; như &ldquo;l&aacute; b&agrave;i độc đắc&rdquo; gi&uacute;p họ c&oacute; thể dễ d&agrave;ng &ldquo;đổi vận&rdquo; từ cảnh đi thu&ecirc; th&agrave;nh những chủ nh&agrave;.&nbsp;</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Theo đ&oacute;, với chương tr&igrave;nh &ldquo;Mua nh&agrave; sang - An t&acirc;m t&agrave;i ch&iacute;nh&rdquo;, người mua trả g&oacute;p được Vinhomes hỗ trợ l&atilde;i suất cố định trong thời gian l&ecirc;n tới 15 năm. Chương tr&igrave;nh được &aacute;p dụng cho sản phẩm nh&agrave; phố tại Vinhomes Ocean Park 2, căn hộ The Zenpark - Vinhomes Ocean Park 1 (H&agrave; Nội) v&agrave; căn hộ The Beverly - Vinhomes Grand Park (TP.HCM).</p>
<figure style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;">&nbsp;</figure>
<p style="text-align: center;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;"><img alt="vin 2.jpg" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" srcset="https://static-images.vnncdn.net/files/publish/2024/3/13/vin-2-767.jpg?width=0&s=pJijW3tPvkF-vofzDGQH7g" style="border: 0px;"></p>`,
    },
    {
      id: "don-chan-song-chu-ky-bat-dong-san-nha-dau-tu-san-lung-nhung-san-pham-co-chinh-sach-khung",
      img: "https://storage.googleapis.com/vinhomes-data-02/styles/images_263_x_146/public/2024_04/Screenshot 2024-04-09 at 10_1712632539.png?itok=w5zRMstS",
      title:
        "Đón “chân sóng” chu kỳ bất động sản, nhà đầu tư săn lùng những sản phẩm có chính sách khủng",
      content: `<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;"><strong><strong>Bất động sản vẫn kh&oacute; h&atilde;m đ&agrave; tăng gi&aacute;</strong></strong></p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Trong 5 năm qua, gi&aacute; nh&agrave; đ&atilde; tăng trưởng mạnh mẽ v&agrave; được cho l&agrave; sẽ tiếp tục đi l&ecirc;n trong tương lai.&nbsp;Theo thống k&ecirc; của Savills, gi&aacute; sơ cấp căn hộ đ&atilde; tăng li&ecirc;n tục trong v&ograve;ng 20 qu&yacute; trở lại đ&acirc;y, hiện đ&atilde; đạt tới 58 triệu đồng/m2.&nbsp;C&aacute;c dự &aacute;n căn hộ mới khoảng gi&aacute; trung b&igrave;nh l&agrave;&nbsp;51 &ndash; 70 triệu đồng/m2. V&agrave; trong số c&aacute;c căn hộ b&aacute;n được năm 2023, c&oacute; tới 42% c&oacute; gi&aacute; tr&ecirc;n 4 tỷ đồng.</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Nguy&ecirc;n&nbsp;do cơ bản&nbsp;khiến&nbsp;gi&aacute; căn hộ&nbsp;tăng phi m&atilde;&nbsp;đ&atilde; được giới chuy&ecirc;n m&ocirc;n mổ xẻ cặn kẽ,&nbsp;theo đ&oacute; trước ti&ecirc;n l&agrave; do&nbsp;nguồn cung khan hiếm đến cực đoan. Năm 2023 ghi nhận nguồn cung mới chỉ hơn 1 vạn căn, thấp nhất trong 10 năm qua. Trong khi đ&oacute;&nbsp;chi ph&iacute; ph&aacute;t triển dự &aacute;n ng&agrave;y c&agrave;ng lớn&nbsp;như&nbsp;tiền sử dụng đất cao, gi&aacute; vật liệu tăng vọt, gi&aacute; nh&acirc;n c&ocirc;ng đắt, l&atilde;i suất cho vay duy tr&igrave; ở mức 2 chữ số&hellip;</p>
<table align="center" style="text-align: justify;color: rgb(255, 255, 255);background-color: rgb(255, 255, 255);font-size: 14px;border-collapse: collapse;">
    <tbody>
        <tr style="color: rgb(34, 34, 34);border: 1px solid rgb(221, 221, 221);">
            <td style="text-align: center;color: rgb(34, 34, 34);border: 1px solid rgb(221, 221, 221);"><img alt="Nhiều chuyên gia đánh giá, thị trường đang ở giai đoạn tốt để người dân sớm sở hữu nhà " src="https://vnmedia.vn/file/8a10a0d36ccebc89016ce0c6fa3e1b83/042024/1_20240404182530.jpeg" style="border: 0px;"></td>
        </tr>
        <tr style="color: rgb(34, 34, 34);border: 1px solid rgb(221, 221, 221);">
            <td style="text-align: center;color: rgb(34, 34, 34);border: 1px solid rgb(221, 221, 221);">Nhiều chuy&ecirc;n gia đ&aacute;nh gi&aacute;, thị trường đang ở giai đoạn tốt để người d&acirc;n sớm sở hữu nh&agrave;</td>
        </tr>
    </tbody>
</table>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Mặc d&ugrave; nguồn cung đ&atilde; c&oacute; dấu hiệu cải thiện tuy nhi&ecirc;n lực cầu lớn đ&atilde; khiến tỷ lệ hấp thụ 6 th&aacute;ng cuối năm 2023 tăng mạnh. Số liệu từ VnDirect cho thấy, tại H&agrave; Nội, cả nguồn cung mới v&agrave; doanh số đi l&ecirc;n r&otilde; rệt qua c&aacute;c qu&yacute;, với tỷ lệ hấp thụ tr&ecirc;n 100%. Tại TP.HCM, số lượng căn hộ b&aacute;n ra nửa cuối năm cao hơn 101% so với nửa đầu năm, tỷ lệ hấp thụ đạt 108%, gần gấp đ&ocirc;i so với nửa đầu năm.&nbsp;</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">B&ecirc;n cạnh đ&oacute;, theo đ&aacute;nh gi&aacute; của VnDirect, Việt Nam đang trong thời kỳ d&acirc;n số v&agrave;ng, với tỷ trọng người trong độ tuổi lao động cao, 31,5% d&acirc;n số nằm trong độ tuổi 25 &ndash; 44. Đ&acirc;y vừa l&agrave; động lực ph&aacute;t triển thị trường nh&agrave; ở nhưng cũng sẽ khiến nguồn cungtrong d&agrave;i hạn kh&ocirc;ng theo kịp nhu cầu.&nbsp;</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Theo c&aacute;c chuy&ecirc;n gia, điều n&agrave;y cũng c&oacute; nghĩa đ&agrave; tăng gi&aacute; nh&agrave; sẽ kh&ocirc;ng thể dừng lại. T&igrave;nh thế n&agrave;y dẫn đến một thực trạng l&agrave; người n&agrave;o c&agrave;ng đắn đo, chờ đợi, nu&ocirc;i hi vọng gi&aacute; nh&agrave; giảm th&igrave; cơ hội sở hữu nh&agrave; sẽ c&agrave;ng &iacute;t đi.&nbsp;</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Thậm ch&iacute;, nếu chậm ch&acirc;n th&ecirc;m 1 năm nữa, khả năng mua nh&agrave; c&oacute; thể giảm về mức tiệm cận &ldquo;0&rdquo;, do nguồn cung sẽ kh&ocirc;ng c&oacute; cải thiện đ&aacute;ng kể n&agrave;o trong năm 2024. Bởi vậy, giới chuy&ecirc;n m&ocirc;n cho rằng, thay v&igrave; chờ đợi, kh&aacute;ch h&agrave;ng n&ecirc;n mua nh&agrave; sớm nhất c&oacute; thể, đ&acirc;y&nbsp;l&agrave; giai đoạn tốt cuối c&ugrave;ng để mua v&agrave;o.</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;"><strong><strong>&ldquo;Bom tấn&rdquo;&nbsp;ph&aacute; vỡ th&ocirc;ng lệ của phương thức mua trả g&oacute;p</strong></strong></p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Hiện nay, mặt bằng l&atilde;i suất cho vay đ&atilde; giảm 2,0&nbsp;-&nbsp;2,5% kể từ đỉnh. C&aacute;c chủ đầu tư kh&ocirc;ng chỉ dễ d&agrave;ng tiếp cận nguồn vốn m&agrave; c&ograve;n giảm bớt được g&aacute;nh nặng l&atilde;i vay. Hơn nữa, nhiều chủ đầu tư c&oacute; năng lực t&agrave;i ch&iacute;nh mạnh cũng đ&atilde; đưa ra c&aacute;c&nbsp;ch&iacute;nh&nbsp;s&aacute;ch&nbsp;thanh to&aacute;n với l&atilde;i suất ưu đ&atilde;i để hỗ trợ nhu cầu của người mua nh&agrave;.</p>
<table align="center" style="text-align: justify;color: rgb(255, 255, 255);background-color: rgb(255, 255, 255);font-size: 14px;border-collapse: collapse;">
    <tbody>
        <tr style="color: rgb(34, 34, 34);border: 1px solid rgb(221, 221, 221);">
            <td style="color: rgb(34, 34, 34);border: 1px solid rgb(221, 221, 221);"><img alt="Chính sách của Vinhomes được đánh giá đã phá vỡ những quy luật trong chính sách mua vay trả góp" src="https://vnmedia.vn/file/8a10a0d36ccebc89016ce0c6fa3e1b83/042024/2_20240404182616.jpeg" style="border: 0px;"></td>
        </tr>
        <tr style="color: rgb(34, 34, 34);border: 1px solid rgb(221, 221, 221);">
            <td style="text-align: center;color: rgb(34, 34, 34);border: 1px solid rgb(221, 221, 221);">Ch&iacute;nh s&aacute;ch của Vinhomes được đ&aacute;nh gi&aacute; đ&atilde; ph&aacute; vỡ những quy luật trong ch&iacute;nh s&aacute;ch mua vay trả g&oacute;p</td>
        </tr>
    </tbody>
</table>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Đ&aacute;ng ch&uacute; &yacute; nhất ch&iacute;nh l&agrave; Vinhomes với ch&iacute;nh s&aacute;ch trả g&oacute;p chưa từng c&oacute; tiền lệ, &aacute;p dụng l&atilde;i suất cố định &ldquo;kh&ocirc;ng c&oacute; đối thủ&rdquo; tr&ecirc;n thị trường. Theo đ&oacute;, kh&aacute;ch vay mua sản phẩm thấp tầng tại Vinhomes Ocean Park 2 hay ph&acirc;n khu căn hộ The Zenpark tại Vinhomes Ocean Park 1 v&agrave; The Beverly tại Vinhomes Grand Park được hưởng mức l&atilde;i suất thấp kỷ lục tương ứng 6% v&agrave; 7% trong 2 năm đầu. Sau 2 năm, l&atilde;i suất vay được &ldquo;thả nổi&rdquo; với trần tương ứng 8% (thấp tầng) v&agrave; 9,5% (căn hộ), thời hạn vay k&eacute;o d&agrave;i tới 15 năm.&nbsp;</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Với ch&iacute;nh s&aacute;ch của Vinhomes, người mua c&oacute; thể ho&agrave;n to&agrave;n an t&acirc;m v&agrave; chủ động được phương &aacute;n t&agrave;i ch&iacute;nh. Nếu l&atilde;i suất thực tế của ng&acirc;n h&agrave;ng thấp hơn, người mua sẽ được hưởng đ&uacute;ng mức l&atilde;i suất ng&acirc;n h&agrave;ng &aacute;p dụng. Nếu l&atilde;i suất thực tế của ng&acirc;n h&agrave;ng cao hơn, người mua&nbsp;cũng&nbsp;chỉ phải trả l&atilde;i với mức trần tối đa l&agrave; 8hoặc 9,5%/năm. To&agrave;n bộ phần ch&ecirc;nh lệch l&atilde;i suất,&nbsp;nếu c&oacute;,&nbsp;sẽ do Vinhomes chịu tr&aacute;ch nhiệm chi trả cho ng&acirc;n h&agrave;ng.</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Giới chuy&ecirc;n gia cho rằng, d&ugrave; l&atilde;i suất thả nổi tại c&aacute;c&nbsp;ng&acirc;n&nbsp;h&agrave;ng thương mại đ&atilde; giảm nhưng hiện vẫn dao động từ 11% trở l&ecirc;n.&nbsp;Do đ&oacute;, với mức trần&nbsp;cố định&nbsp;chỉ 8&nbsp;- 9,5%,&nbsp;c&oacute; thể n&oacute;i&nbsp;ch&iacute;nh s&aacute;ch của Vinhomes đ&atilde; ph&aacute; vỡ những quy luật&nbsp;trong ch&iacute;nh s&aacute;ch mua vay trả g&oacute;p. Điều đ&oacute; cũng l&yacute; giải v&igrave; sao người mua đang&nbsp;đổ về&nbsp;Vinhomes Ocean Park 1, 2 v&agrave; Vinhomes Grand Park, đua nhau săn l&ugrave;ng những sản phẩm cuối c&ugrave;ng.</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Dưới g&oacute;c nh&igrave;n của&nbsp;doanh nghiệp,&nbsp;gi&aacute;m đốc một&nbsp;c&ocirc;ng ty BĐS tại H&agrave; Nội cho rằng d&ograve;ng tiền đổ v&agrave;o c&aacute;c dự &aacute;n của Vinhomes l&uacute;c n&agrave;y l&agrave; đương nhi&ecirc;n.&nbsp;Nh&agrave; đầu tư s&agrave;nh sỏi sẽ nh&igrave;n thấy r&otilde;, đ&acirc;y l&agrave; những sản phẩm cuối c&ugrave;ng c&ograve;n s&oacute;t lại được tạo lập ở giai đoạn trước - thời điểm c&aacute;c yếu tố cấu th&agrave;nh gi&aacute; b&aacute;n c&ograve;n ở mức rẻ,&nbsp;nay c&oacute;&nbsp;th&ecirc;m ch&iacute;nh s&aacute;ch hỗ trợ trả g&oacute;p cố định&nbsp;l&atilde;i suất&nbsp;thấp trong thời gian d&agrave;i.&nbsp;V&igrave; thế, đ&acirc;y&nbsp;l&agrave; khoản đầu tư rất hời&nbsp;gi&uacute;p kh&aacute;ch h&agrave;ng&nbsp;sở hữu&nbsp;ngay&nbsp;nh&agrave; sang,&nbsp;m&ocirc;i trường sống đẳng cấp&nbsp;với&nbsp;số vốn&nbsp;ban đầu&nbsp;chỉ 30%&nbsp;gi&aacute; trị sản phẩm.</p>
<p style="text-align: justify;color: rgb(34, 34, 34);background-color: rgb(255, 255, 255);font-size: 13px;">Luật Đất đai sửa đổi dự kiến sẽ c&oacute; hiệu lực thi h&agrave;nh sớm ngay từ 1/7/2024, được nhận định sẽ l&agrave; c&uacute; h&iacute;ch khiến thị trường BĐS c&agrave;ng th&ecirc;m s&ocirc;i động. V&igrave; thế, xuống tiền v&agrave;o thời điểm n&agrave;y, nh&agrave; đầu tư sẽ hưởng lợi k&eacute;p khi vừa sở hữu được sản phẩm đẳng cấp với gi&aacute; hợp l&yacute;, vừa nắm chắc lợi nhuận khi mặt bằng gi&aacute; mới sắp được thiết lập, trong khi vẫn tối ưu được d&ograve;ng vốn nhờ ch&iacute;nh s&aacute;ch trả g&oacute;p vượt trội của Vinhomes.</p>`,
    },
    {
      id: "kham-pha-chuan-song-khac-biet-tai-ocean-city",
      img: "https://storage.googleapis.com/vinhomes-data-02/styles/images_263_x_146/public/2024_04/Screenshot 2024-04-09 at 10_1712632323.png?itok=oCnv8InD",
      title: "Khám phá 'chuẩn sống' khác biệt tại Ocean City",
      content: `Ocean City đang là nơi an cư đáng mơ ước của hơn 60.000 cư dân cả trong và ngoài nước bởi những giá trị sống khác biệt chỉ có tại “nơi đáng sống nhất hành tinh”.
Ocean City đang là nơi an cư đáng mơ ước của hơn 60.000 cư dân cả trong và ngoài nước bởi những giá trị sống khác biệt chỉ có tại “nơi đáng sống nhất hành tinh”.

Với truyền thông quốc tế, Ocean City là một trong những cái tên nổi bật nhất trên thị trường bất động sản Việt Nam hiện nay. Mới đây, thành phố điểm đến Ocean City phía đông thủ đô của Vinhomes được tờ Straits Times - nhật báo hàng đầu Singapore - đánh giá là lựa chọn hàng đầu của công dân toàn cầu thế hệ mới khi đón đầu xu hướng xanh hóa trên thị trường bất động sản. 

Bắt trọn chất “sống xanh” tiêu chuẩn toàn cầu
"Khu phức hợp siêu lớn này định nghĩa lại cuộc sống đô thị, mang đến cho cư dân một cuộc sống lành mạnh và trọn vẹn với nhiều trải nghiệm - trái ngược hoàn toàn với những con phố chật chội và tiếng ồn ào đơn điệu của các siêu đô thị truyền thống", tờ Strait Times nhận định.


Ocean City anh 1
Không gian tràn ngập màu xanh và mang đậm hơi thở của sự trong lành tại Ocean City.

Lấy tiêu chuẩn quốc tế làm “thước đo” trong quy hoạch, các công trình tại Ocean City đều được xây dựng với mật độ dưới 30% kết hợp cùng hơn 1,5 triệu m2 không gian xanh. Như vậy, mỗi cư dân tại Ocean City sẽ có riêng cho mình diện tích từ 2 m2 đến 4 m2 “không khí trong lành”. Cùng với đó, mỗi không gian nhà ở dù thấp tầng hay cao tầng đều được “xanh hóa” đón gió và ánh sáng tự nhiên.

“Bãi biển” trong xanh ngay trong lòng thủ đô thu hút cư dân và nhiều khách du lịch.

Ocean City anh 2
“Bãi biển” trong xanh ngay trong lòng thủ đô thu hút cư dân và nhiều khách du lịch.

Không chỉ mang đến không gian xanh, Ocean City còn là nơi đầu tiên và duy nhất “mang biển” về thủ đô, tạo nên chất sống xanh đẳng cấp hàng đầu khu vực. Theo Yahoo Finance, Ocean City đưa những chuyến nghỉ dưỡng chữa lành bên bờ biển đến ngay trước cửa nhà. Theo đó, tại đây có biển hồ nhân tạo lớn nhất thế giới Crystal Lagoon, hồ nước ngọt với bãi cát trắng nguyên sơ tại biển hồ Ngọc Trai, cùng tổ hợp hồ nước mặn tạo sóng nhân tạo trong khuôn viên đô thị lớn nhất thế giới VinWonders Hanoi Wave Park.

Tại Ocean City, sống xanh không chỉ dừng lại ở không gian, mà còn thể hiện ở thói quen tích cực qua những hành động thiết thực. Cư dân Ocean City có thể dễ dàng di chuyển trong nội khu hay tới nhiều địa điểm khác trên địa bàn TP Hà Nội nhờ dịch vụ taxi điện Xanh SM và hệ thống xe buýt điện VinBus. Nơi đây cũng khuyến khích cư dân sử dụng phương tiện giao thông xanh khi bố trí hệ thống trạm sạc ôtô và xe máy điện rộng khắp. 

Trong không gian mát lành, hàng loạt tiện ích sức khỏe được bố trí rộng khắp đại đô thị như sân thể thao ngoài trời với hơn 700 máy tập, công viên quần vợt, công viên golf mặt nước, hồ bơi bốn mùa… 

Vạn tiện ích đắt giá trước cửa nhà
Bên cạnh hệ thống tiện ích cảnh quan xanh “hút mắt”, Ocean City còn quy tụ đa dạng tiện ích giải trí, mua sắm, giáo dục, chăm sóc sức khỏe cao cấp, xứng đáng trở thành nơi an cư “đáng sống nhất hành tinh”.

Trường Đại học tiêu chuẩn quốc tế VinUni hướng đến mục tiêu trở thành một trong 50 đại học hàng đầu thế giới.

Ocean City anh 3
Trường Đại học tiêu chuẩn quốc tế VinUni hướng đến mục tiêu trở thành một trong 50 đại học hàng đầu thế giới.

Nhờ được quy hoạch theo mô hình đô thị “all-in-one”, cư dân Ocean City cũng có thể sử dụng tất cả tiện ích phục vụ đời sống được tích hợp ngay dưới chân tòa nhà, không cần di chuyển xa. Từ các tổ hợp mua sắm - giải trí hàng đầu như Grand World, khu phức hợp Center Point, TTTM Vincom Mega cho đến các đại tiện ích phục vụ nhu cầu cuộc sống như bệnh viện quốc tế Vinmec, trường đại học VinUni… đều được xây dựng theo tiêu chuẩn quốc tế cao cấp.

Trở thành cư dân Ocean City hơn nửa năm, nhưng với John Trần - Giám đốc công ty phần mềm có văn phòng tại Techno Park - chia sẻ: “Tôi thường kể với bạn bè quốc tế rằng Ocean City - nơi tôi sống có mọi thứ, thậm chí còn hơn thế nữa. Từ việc đi làm, mua sắm, học hành cho đến tận hưởng kỳ nghỉ bên biển, tất cả được gói gọn trong khu đô thị”.

VinWonders là điểm nhấn tạo nên sự khác biệt của Ocean City, nơi du lịch - vui chơi giải trí - nghệ thuật hòa quyện với cuộc sống thường nhật.​​​​​​​​​​​​​​

Ocean City anh 4
VinWonders là điểm nhấn tạo nên sự khác biệt của Ocean City, nơi du lịch - vui chơi giải trí - nghệ thuật hòa quyện với cuộc sống thường nhật.

Bên cạnh chuẩn sống đẳng cấp - văn minh, đời sống tinh thần của cư dân Ocean City nói riêng và các đại đô thị Vinhomes trên toàn quốc nói chung cũng được chủ đầu tư quan tâm. Sau gần 3 tháng hoạt động, CLB Sống vui - khỏe và CLB Sống xanh - văn minh - đẳng cấp do Vinhomes thành lập đã nhận về nhiều sự quan tâm, ủng hộ của cư dân.

Nếu như CLB Sống xanh - văn minh - đẳng cấp đã trở thành điểm hẹn cho những tâm hồn “xanh” muốn đóng góp vào việc bảo vệ môi trường sống, thì CLB Sống vui - khỏe lại mở ra một không gian văn hóa đa dạng, nơi cư dân có thể chia sẻ và trau dồi kiến thức về sức khỏe, văn hóa, nghệ thuật và những lĩnh vực có sự đồng điệu. 

"Vinhomes đã tạo ra những khu đô thị sôi động vượt xa ‘chuẩn’ sống xanh đơn thuần, mang lại chất lượng cuộc sống vượt trội, khiến cộng đồng cư dân trở thành một trong những cộng đồng đáng mơ ước trên Trái Đất”, nhận định của Technode Global về Ocean City và chủ đầu tư Vinhomes đã một lần nữa khẳng định sức hút và “chuẩn sống” khác biệt tại thành phố đáng sống này.`,
    },
    {
      id: "cu-dan-vinhomes-hao-hưng-tham-gia-loat-hoat-dong-dac-quyen-tai-2-clb-cong-dong",
      img: "https://storage.googleapis.com/vinhomes-data-02/styles/images_263_x_146/public/2024_03/club pr1_1711505461.png?itok=XnjVqyCf",
      title:
        "Cư dân Vinhomes hào hứng tham gia loạt hoạt động đặc quyền tại 2 CLB cộng đồng",
      content: `<h2 style="text-align: justify;color: rgb(47, 47, 47);background-color: rgb(255, 255, 255);font-size: 16px;">Chỉ sau hơn 1 th&aacute;ng c&ocirc;ng bố chiến lược n&acirc;ng tầm chuẩn sống tại c&aacute;c khu đ&ocirc; thị, c&aacute;c CLB động đồng của Vinhomes với h&agrave;ng loạt hoạt động, trải nghiệm hấp dẫn đ&atilde; được đ&ocirc;ng đảo cư d&acirc;n đ&oacute;n nhận nồng nhiệt.</h2>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;">
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><strong><b>Những</b></strong><strong><b>&nbsp;</b></strong><strong><b>đặc</b></strong><strong><b>&nbsp;</b></strong><strong><b>quyền</b></strong><strong><b>&nbsp;</b></strong><strong><b>n&acirc;ng</b></strong><strong><b>&nbsp;</b></strong><strong><b>tầm</b></strong><strong><b>&nbsp;</b></strong><strong><b>chuẩn</b></strong><strong><b>&nbsp;</b></strong><strong><b>sống</b></strong></p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Hoạt động cộng đồng đa dạng, năng động l&agrave; một trong những thế mạnh vốn c&oacute; tại c&aacute;c khu đ&ocirc; thị của Vinhomes. Với mục ti&ecirc;u th&uacute;c đẩy c&aacute;c hoạt động n&agrave;y l&ecirc;n một tầm cao mới, chuy&ecirc;n nghiệp v&agrave; lan tỏa mạnh mẽ hơn trong cộng đồng cư d&acirc;n, Vinhomes đ&atilde; triển khai chiến lược n&acirc;ng tầm chuẩn sống với sự ra mắt của 2 CLB l&agrave; Sống Xanh &ndash; Văn minh &ndash; Đẳng cấp v&agrave; Sống Vui &ndash; Khỏe.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Chỉ sau một thời gian ngắn, Vinhomes đ&atilde; tận dụng v&agrave; ph&aacute;t huy tất cả lợi thế trong c&ocirc;ng t&aacute;c vận h&agrave;nh chuy&ecirc;n nghiệp sẵn c&oacute;, kết hợp c&aacute;c thương hiệu kh&aacute;c trong hệ sinh th&aacute;i Vingroup để đưa c&aacute;c CLB v&agrave;o hoạt động. C&aacute;c CLB n&agrave;y đ&atilde; thu h&uacute;t được nhiều th&agrave;nh vi&ecirc;n tham gia ngay trong th&aacute;ng đầu ti&ecirc;n ra mắt, đồng thời nhận được sự ủng hộ nhiệt t&igrave;nh của cộng đồng cư d&acirc;n c&aacute;c khu đ&ocirc; thị.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><img alt="Cư dân Vinhomes hào hứng tham gia loạt hoạt động đặc quyền tại 2 CLB cộng đồng - Ảnh 2." height="404" rel="lightbox" src="https://afamilycdn.com/150157425591193600/2024/2/21/photo-1-17085054350181347763470-1708514552120-1708514552548115468635.png" title="Cư dân Vinhomes hào hứng tham gia loạt hoạt động đặc quyền tại 2 CLB cộng đồng - Ảnh 2." type="photo" width="606" style="border: 0px;"></p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;">C&aacute;c hoạt động diễn ra s&ocirc;i động tại c&aacute;c khu đ&ocirc; thị với sự tham gia của nhiều thế hệ cư d&acirc;n</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Đơn cử tại khu đ&ocirc; thị Vinhomes Times City, c&aacute;c th&agrave;nh vi&ecirc;n của CLB Sống Vui &ndash; Khỏe đ&atilde; c&ugrave;ng nhau tham gia c&aacute;c buổi học dưỡng sinh kh&oacute;a đầu ti&ecirc;n với sự hướng dẫn của c&aacute;c b&aacute;c sĩ y học cổ truyền. Cộng đồng cư d&acirc;n c&ograve;n được tham gia c&aacute;c hoạt động giao lưu nghệ thuật, vẽ tranh thư ph&aacute;p, tr&agrave; đạo v&agrave; tham dự tọa đ&agrave;m sức khỏe, với c&aacute;c kiến thức Đ&ocirc;ng &ndash; T&acirc;y y kết hợp được c&aacute;c diễn giả l&agrave; chuy&ecirc;n gia về sức khỏe, y tế diễn giải một c&aacute;ch khoa học v&agrave; dễ hiểu.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><img alt="Cư dân Vinhomes hào hứng tham gia loạt hoạt động đặc quyền tại 2 CLB cộng đồng - Ảnh 3." height="957" rel="lightbox" src="https://afamilycdn.com/150157425591193600/2024/2/21/photo-2-1708505436793128493702-1708514553212-17085145536641185359111.png" title="Cư dân Vinhomes hào hứng tham gia loạt hoạt động đặc quyền tại 2 CLB cộng đồng - Ảnh 3." type="photo" width="638" style="border: 0px;"></p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;">C&aacute;c th&agrave;nh vi&ecirc;n CLB sẽ li&ecirc;n tục được tham gia c&aacute;c hoạt động chăm s&oacute;c sức khỏe chuy&ecirc;n nghiệp</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Đặc biệt, với sự g&oacute;p mặt của Trung t&acirc;m Y học cổ truyền Vinmec &ndash; Sao Phương Đ&ocirc;ng, c&aacute;c th&agrave;nh vi&ecirc;n c&ograve;n được trải nghiệm c&aacute;c hoạt động, dịch vụ chăm s&oacute;c v&agrave; bảo vệ sức khỏe cơ &ndash; xương &ndash; khớp với c&aacute;c phương ph&aacute;p bấm huyệt, chuẩn trị bằng Đ&ocirc;ng y rất hiệu quả.</p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;"><img alt="Cư dân Vinhomes hào hứng tham gia loạt hoạt động đặc quyền tại 2 CLB cộng đồng - Ảnh 4." height="426" rel="lightbox" src="https://afamilycdn.com/150157425591193600/2024/2/21/photo-3-17085054361251766461873-1708514554202-1708514554396711057186.png" title="Cư dân Vinhomes hào hứng tham gia loạt hoạt động đặc quyền tại 2 CLB cộng đồng - Ảnh 4." type="photo" width="638" style="border: 0px;"></p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;">C&aacute;c buổi hội thảo, tọa đ&agrave;m với sự g&oacute;p mặt của c&aacute;c chuy&ecirc;n gia sức khỏe đ&atilde; cung cấp cho c&aacute;c th&agrave;nh vi&ecirc;n nhiều kiến thức mới</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Song song với c&aacute;c hoạt động s&ocirc;i nổi của CLB Sống Vui &ndash; Khỏe, c&aacute;c hoạt động của CLB Sống Xanh &ndash; Văn minh &ndash; Đẳng cấp cũng tạo ra kh&ocirc;ng kh&iacute; s&ocirc;i động, t&iacute;ch cực ngay trong những tuần đầu ti&ecirc;n hoạt động, th&uacute;c đẩy c&aacute;c hoạt động cộng đồng tại c&aacute;c khu đ&ocirc; thị. Như tại Vinhomes Ocean Park 2, CLB Sống Xanh &ndash; Văn minh &ndash; Đẳng cấp đ&atilde; t&agrave;i trợ, hỗ trợ CLB Tennis tổ chức giải đấu giao lưu đầu năm mới với sự tham gia nhiệt t&igrave;nh của h&agrave;ng trăm th&agrave;nh vi&ecirc;n.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">B&ecirc;n cạnh đ&oacute;, CLB n&agrave;y cũng duy tr&igrave; c&aacute;c hoạt động sống xanh tại c&aacute;c khu đ&ocirc; thị của Vinhomes với c&aacute;c hoạt động chia sẻ kinh nghiệm sống xanh, l&agrave;nh mạnh, tiết kiệm. Đặc biệt l&agrave; c&aacute;c hoạt động thực h&agrave;nh 5T (Tiết kiệm năng lượng, tiết kiệm nước, t&aacute;i chế, trồng c&acirc;y, t&iacute;ch điểm xanh) đang lan tỏa rộng r&atilde;i kh&ocirc;ng chỉ trong CLB m&agrave; c&ograve;n với to&agrave;n thể cư d&acirc;n. Điển h&igrave;nh l&agrave; chương tr&igrave;nh &quot;Giờ xanh Vinhomes &ndash; Tắt điện sớm 15 ph&uacute;t mỗi ng&agrave;y&quot; đang được c&aacute;c gia đ&igrave;nh hưởng ứng h&agrave;ng ng&agrave;y, gi&uacute;p giảm lượng ti&ecirc;u thụ điện cho quốc gia, g&oacute;p phần x&acirc;y dựng một thế giới xanh, bền vững.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Cũng trong giai đoạn Tết Gi&aacute;p Th&igrave;n vừa qua, c&aacute;c th&agrave;nh vi&ecirc;n CLB đ&atilde; kết hợp c&ugrave;ng với Quỹ Thiện T&acirc;m của Vingroup gửi tặng hơn một trăm phần qu&agrave; Tết &yacute; nghĩa cho người c&oacute; ho&agrave;n cảnh kh&oacute; khăn đặc biệt tại huyện Bắc Sơn, tỉnh Lạng Sơn. Những nghĩa cử đẹp n&agrave;y kỳ vọng được nh&acirc;n rộng v&agrave; trở th&agrave;nh một trong những hoạt động thường nhật của CLB, gi&uacute;p lan tỏa sự nh&acirc;n văn của một cộng đồng văn minh, đẳng cấp, đồng thời tạo ra điểm đến l&agrave;m từ thiện uy t&iacute;n cho c&aacute;c cư d&acirc;n c&oacute; c&ugrave;ng mong muốn.</p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;"><img alt="Cư dân Vinhomes hào hứng tham gia loạt hoạt động đặc quyền tại 2 CLB cộng đồng - Ảnh 5." height="348" rel="lightbox" src="https://afamilycdn.com/150157425591193600/2024/2/21/photo-4-1708505435553328439042-1708514555397-17085145556281035049474.png" title="Cư dân Vinhomes hào hứng tham gia loạt hoạt động đặc quyền tại 2 CLB cộng đồng - Ảnh 5." type="photo" width="619" style="border: 0px;"></p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;">Đại diện BQT cư d&acirc;n c&aacute;c khu đ&ocirc; thị Vinhomes c&ugrave;ng Quỹ thiện t&acirc;m trao qu&agrave; Tết Gi&aacute;p Th&igrave;n tại huyện Bắc Sơn, tỉnh Lạng Sơn</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><strong><b>Cộng đồng văn minh lớn mạnh từng ng&agrave;y</b></strong></p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Với nỗ lực n&acirc;ng cao chất lượng cuộc sống cho cư d&acirc;n, c&aacute;c CLB Sống Vui &ndash; Khỏe v&agrave; Sống Xanh &ndash; Văn Minh &ndash; Đẳng Cấp đ&atilde; ph&aacute;t huy được hiệu quả r&otilde; rệt khi kh&ocirc;ng chỉ l&agrave; nơi giao lưu, kết nối cộng đồng m&agrave; c&ograve;n l&agrave; biểu tượng của lối sống ti&ecirc;n tiến, hướng tới sự ph&aacute;t triển bền vững to&agrave;n diện cho mỗi cư d&acirc;n trong khu đ&ocirc; thị Vinhomes.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Chỉ sau hơn một th&aacute;ng, sự thay đổi t&iacute;ch cực trong tinh thần v&agrave; h&agrave;nh động của cư d&acirc;n đ&atilde; được lan tỏa v&agrave; trở th&agrave;nh nguồn cảm hứng cho những ai mong muốn c&oacute; một cuộc sống năng động v&agrave; khỏe mạnh. CLB Sống Xanh &ndash; Văn minh &ndash; Đẳng cấp đ&atilde; trở th&agrave;nh điểm hẹn cho những người y&ecirc;u thi&ecirc;n nhi&ecirc;n, quy tụ những t&acirc;m hồn xanh muốn đ&oacute;ng g&oacute;p v&agrave;o việc bảo vệ m&ocirc;i trường sống. Trong khi đ&oacute;, CLB Sống Vui &ndash; Khỏe lại mở ra một kh&ocirc;ng gian văn h&oacute;a đa dạng, nơi cư d&acirc;n c&oacute; thể chia sẻ v&agrave; trau dồi kiến thức kh&ocirc;ng chỉ về sức khỏe m&agrave; c&ograve;n l&agrave; văn h&oacute;a, nghệ thuật v&agrave; những lĩnh vực c&oacute; sự đồng điệu.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Sau thời gian đầu hoạt động, nhiều th&agrave;nh vi&ecirc;n cũng b&agrave;y tỏ sự mong chờ với c&aacute;c hoạt động như trồng c&acirc;y, ph&acirc;n loại r&aacute;c thải v&agrave; tổ chức c&aacute;c sự kiện n&acirc;ng cao &yacute; thức về m&ocirc;i trường, c&aacute;c giải đấu thể thao s&ocirc;i động của CLB Sống Xanh &ndash; Văn minh &ndash; Đẳng cấp hay c&aacute;c hoạt động hội thảo, chăm s&oacute;c sức khỏe, lớp học Yoga Thiền của CLB Sống Vui &ndash; Khỏe sẽ được diễn ra thường xuy&ecirc;n trong thời gian tới.</p>
</div>`,
    },
    {
      id: "cuoc-choi-lon-cua-ty-phu-pham-nhat-vuong-xay-dao-ty-phu-quy-mo-887ha-ban-nha-cho-gioi-thuong-luu-sieu-giau",
      img: "https://storage.googleapis.com/vinhomes-data-02/styles/images_263_x_146/public/2024_03/vy%20pr15_1711444514.jpeg?itok=gcuAqcSr",
      title:
        "Cuộc chơi lớn của tỷ phú Phạm Nhật Vượng: Xây 'đảo tỷ phú' quy mô 877ha, bán nhà cho giới thượng lưu siêu giàu",
      content: `<h2 style="text-align: justify;color: rgb(47, 47, 47);background-color: rgb(255, 255, 255);font-size: 16px;">C&ocirc;ng ty Cổ phần Vinhomes vừa ra mắt dự &aacute;n &ldquo;Th&agrave;nh phố Đảo Ho&agrave;ng Gia&rdquo; &ndash; Vinhomes Royal Island tại đảo Vũ Y&ecirc;n, Hải Ph&ograve;ng - đ&ocirc; thị đảo đầu ti&ecirc;n giữa trung t&acirc;m th&agrave;nh phố.</h2>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;">
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Vinhomes Royal Island c&oacute; quy m&ocirc; 877 h&eacute;cta, tọa lạc trọn vẹn tr&ecirc;n đảo Vũ Y&ecirc;n, kết nối nội đ&ocirc; hiện tại của Hải Ph&ograve;ng với trung t&acirc;m h&agrave;nh ch&iacute;nh mới Thủy Nguy&ecirc;n v&agrave; l&agrave; địa thế &ldquo;đảo trong phố&rdquo; độc đ&aacute;o, duy nhất tr&ecirc;n to&agrave;n quốc.&nbsp;</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Vị tr&iacute; n&agrave;y cho ph&eacute;p dự &aacute;n dễ d&agrave;ng tiếp cận tới c&aacute;c khu vực trong tam gi&aacute;c kinh tế trọng điểm ph&iacute;a Bắc l&agrave; H&agrave; Nội &ndash; Hải Ph&ograve;ng &ndash; Quảng Ninh, cũng như tới c&aacute;c th&agrave;nh phố lớn tr&ecirc;n thế giới th&ocirc;ng qua hệ thống đường kh&ocirc;ng - đường thuỷ - đường bộ.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><img alt="Cuộc chơi lớn của tỷ phú Phạm Nhật Vượng: Xây 'đảo tỷ phú' quy mô 877ha, bán nhà cho giới thượng lưu siêu giàu- Ảnh 1." height="" rel="lightbox" src="https://cafefcdn.com/203337114487263232/2024/3/26/5-1711412160981-1711412161333448221532.png" title="Cuộc chơi lớn của tỷ phú Phạm Nhật Vượng: Xây 'đảo tỷ phú' quy mô 877ha, bán nhà cho giới thượng lưu siêu giàu- Ảnh 1." type="photo" width="" style="border: 0px;"></p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Vinhomes cho biết, địa thế đảo trong phố l&agrave; cơ sở để Vinhomes tạo ra những đặc quyền v&agrave; dịch vụ thượng lưu như: Bến du thuyền cao cấp quy m&ocirc; gần 10ha; S&acirc;n Golf 36 hố 160ha đẳng cấp h&agrave;ng đầu Đ&ocirc;ng Nam &Aacute;; Học viện cưỡi ngựa Ho&agrave;ng Gia; Phố đi bộ b&ecirc;n s&ocirc;ng d&agrave;i v&agrave; đẹp nhất Việt Nam; C&ocirc;ng vi&ecirc;n vui chơi giải tr&iacute; gia đ&igrave;nh VinWonders Royal Park với vườn th&uacute; mở Safari&hellip;&nbsp;</p>
    <figure type="Photo">
        <p style="color: rgb(34, 34, 34);font-size: 13px;"><a href="https://cafefcdn.com/203337114487263232/2024/3/26/vpghplandscape16-1711412162638-17114121629601234794915.jpg" target="_blank" title="" style="color: transparent;"><img alt="Cuộc chơi lớn của tỷ phú Phạm Nhật Vượng: Xây 'đảo tỷ phú' quy mô 877ha, bán nhà cho giới thượng lưu siêu giàu- Ảnh 2." height="" rel="lightbox" src="https://cafefcdn.com/203337114487263232/2024/3/26/vpghplandscape16-1711412162638-17114121629601234794915.jpg" title="Cuộc chơi lớn của tỷ phú Phạm Nhật Vượng: Xây 'đảo tỷ phú' quy mô 877ha, bán nhà cho giới thượng lưu siêu giàu- Ảnh 2." type="photo" width="" style="border: 0px;"></a></p>
    </figure>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Vinhomes cũng cho biết, Vinhomes Royal Island l&agrave; dự &aacute;n đ&ocirc; thị duy nhất tại Việt Nam v&agrave; hiếm hoi tr&ecirc;n thế giới c&oacute; đa số tư gia sở hữu b&atilde;i tắm nước biển ri&ecirc;ng ngay sau nh&agrave;.&nbsp;</p>
    <figure type="Photo">
        <p style="color: rgb(34, 34, 34);font-size: 13px;"><a href="https://cafefcdn.com/203337114487263232/2024/3/26/vpghplandscape24-1711412165037-17114121653272016684114.jpg" target="_blank" title="" style="color: transparent;"><img alt="Cuộc chơi lớn của tỷ phú Phạm Nhật Vượng: Xây 'đảo tỷ phú' quy mô 877ha, bán nhà cho giới thượng lưu siêu giàu- Ảnh 3." height="" rel="lightbox" src="https://cafefcdn.com/203337114487263232/2024/3/26/vpghplandscape24-1711412165037-17114121653272016684114.jpg" title="Cuộc chơi lớn của tỷ phú Phạm Nhật Vượng: Xây 'đảo tỷ phú' quy mô 877ha, bán nhà cho giới thượng lưu siêu giàu- Ảnh 3." type="photo" width="" style="border: 0px;"></a></p>
    </figure>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Về chăm s&oacute;c sức khỏe, c&ugrave;ng với Ph&ograve;ng kh&aacute;m đa khoa Quốc tế Vinmec được đầu tư ngay tr&ecirc;n đảo, lần đầu ti&ecirc;n dịch vụ &ldquo;y tế tận nh&agrave;&rdquo; được Vinhomes v&agrave; Vinmec phối hợp triển khai ngay tại khu đ&ocirc; thị, với 2 nh&aacute;nh dịch vụ l&agrave; kh&aacute;m chữa bệnh v&agrave; chăm s&oacute;c y tế tại chỗ. Dịch vụ n&agrave;y&nbsp;bao gồm mời b&aacute;c sỹ/điều dưỡng thăm kh&aacute;m, k&ecirc; đơn, giao thuốc, lấy mẫu x&eacute;t nghiệm&hellip;; Chăm s&oacute;c mẹ sau sinh v&agrave; b&eacute;, người cao tuổi, hậu phẫu... tại nh&agrave;.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><img alt="Cuộc chơi lớn của tỷ phú Phạm Nhật Vượng: Xây 'đảo tỷ phú' quy mô 877ha, bán nhà cho giới thượng lưu siêu giàu- Ảnh 4." height="" rel="lightbox" src="https://cafefcdn.com/203337114487263232/2024/3/26/1-1711412166601-1711412166945194636003.png" title="Cuộc chơi lớn của tỷ phú Phạm Nhật Vượng: Xây 'đảo tỷ phú' quy mô 877ha, bán nhà cho giới thượng lưu siêu giàu- Ảnh 4." type="photo" width="" style="border: 0px;"></p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Dự &aacute;n c&oacute; diện t&iacute;ch c&acirc;y xanh, mặt nước l&ecirc;n tới 359ha, 31 c&ocirc;ng vi&ecirc;n, 10 bể bơi trong nh&agrave; v&agrave; ngo&agrave;i trời, tổ hợp s&acirc;n tennis, s&acirc;n cầu l&ocirc;ng, b&oacute;ng đ&aacute;, b&oacute;ng chuyền, c&aacute;c vườn tập dưỡng sinh, Gym&hellip; bao phủ khắp dự &aacute;n.&nbsp;</p>
</div>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;"><br></div> `,
    },
    {
      id: "lo-dien-dien-den-an-cu-dau-tu-moi-khien-gioi-nha-giau-quoc-te-dung-ngoi-khong-yen",
      img: "https://storage.googleapis.com/vinhomes-data-02/styles/images_263_x_146/public/2024_03/vy pr14_1711443464.jpeg?itok=-Nlpbb14",
      title: `
Lộ diện điểm đến an cư, đầu tư mới khiến giới nhà giàu quốc tế “đứng ngồi không yên”`,
      content: `<p>Sau Dubai, Miami hay Monaco, giới nh&agrave; gi&agrave;u quốc tế đang đổ dồn sự ch&uacute; &yacute; về Th&agrave;nh phố đảo Ho&agrave;ng Gia Vinhomes Royal Island - &ldquo;đảo tỷ ph&uacute;&rdquo; vừa ra mắt ch&iacute;nh thức ng&agrave;y 21/3 tr&ecirc;n Vinhomes Market - để săn t&igrave;m sản phẩm tiềm năng cho kế hoạch an cư v&agrave; đầu tư năm 2024.</p>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;">
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><strong><strong>Bất động sản &ldquo;c&oacute; gu&rdquo; - Ch&igrave;a kh&oacute;a gia tăng t&agrave;i sản của người gi&agrave;u</strong></strong></p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">1% số người gi&agrave;u nhất thế giới nắm giữ tới 44,5% tổng t&agrave;i sản to&agrave;n cầu. Danh s&aacute;ch n&agrave;y, t&iacute;nh đến năm 2022 c&oacute; sự tham dự của 579.000 gương mặt ở c&aacute;c quốc gia v&agrave; v&ugrave;ng l&atilde;nh thổ, c&ugrave;ng với khoảng 70 triệu c&aacute;i t&ecirc;n đ&atilde; đủ ti&ecirc;u chuẩn để được gọi l&agrave; &ldquo;người gi&agrave;u&rdquo;. Vấn đề được c&ocirc;ng ch&uacute;ng quan t&acirc;m l&agrave; tầng lớp tinh hoa n&agrave;y đ&atilde; gia tăng khối t&agrave;i sản khổng lồ của m&igrave;nh như thế n&agrave;o?</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Khảo s&aacute;t của Knight Frank, thực hiện với hơn 500 người si&ecirc;u gi&agrave;u, đại diện cho khối t&agrave;i sản tổng cộng hơn 2.500 tỉ USD cho thấy: hơn 50% d&ograve;ng tiền của những người n&agrave;y chảy v&agrave;o bất động sản. Cụ thể, khoản đầu tư nhiều nhất l&agrave; nh&agrave; ở ch&iacute;nh v&agrave; bất động sản thứ 2, thứ 3&hellip; chiếm 32%; 21% được đưa trực tiếp v&agrave;o bất động sản thương mại v&agrave; 13% đầu tư th&ocirc;ng qua quỹ nợ hoặc ủy th&aacute;c đầu tư bất động sản.</p>
    <figure><a title="" style="color: transparent;"><img alt="lo dien diem den an cu dau tu moi cua gioi nha giau quoc te hinh 1" height="675" src="https://congluan-cdn.congluan.vn/files/content/2024/03/23/lo-dien-diem-den-an-cu-dau-tu-moi-cua-gioi-nha-giau-quoc-te-091753110.jpg" width="1200" style="border: 0px;"></a>
        <figcaption>
            <p style="color: rgb(34, 34, 34);font-size: 13px;">Th&agrave;nh phố đảo Ho&agrave;ng Gia Vinhomes Royal Island l&agrave; điểm đến mới của giới thượng lưu</p>
        </figcaption>
    </figure>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Tuy nhi&ecirc;n, kh&ocirc;ng phải dự &aacute;n bất động sản n&agrave;o cũng đ&aacute;p ứng đ&uacute;ng &ldquo;khẩu vị&rdquo; đầu tư của giới si&ecirc;u gi&agrave;u quốc tế. Để lọt v&agrave;o &ldquo;mắt xanh&rdquo; của những người s&agrave;nh sỏi, sản phẩm phải cho thấy sự vượt trội về c&aacute;c yếu tố vị tr&iacute;, cảnh quan, những yếu độc bản trong thiết kế hay tiện &iacute;ch đặc quyền gi&uacute;p n&acirc;ng cao chất lượng cuộc sống.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Đặc biệt, kể từ sau đại dịch Covid-19, c&aacute;c ti&ecirc;u chuẩn ng&agrave;y c&agrave;ng quan trọng l&agrave; kh&ocirc;ng gian sống ri&ecirc;ng tư, biệt lập, những trải nghiệm mới lạ, theo hướng c&aacute; nh&acirc;n h&oacute;a như th&uacute; chơi sở hữu du thuyền hay bổ sung th&ecirc;m c&aacute;c dịch vụ chăm s&oacute;c, bảo vệ sức khỏe cao cấp cho cư d&acirc;n&hellip;</p>
</div>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;"><br></div>`,
    },
    {
      id: "co-gi-tai-thanh-pho-dao-hoang-gia-vinhomes-royal-island-vua-ra-mat",
      img: "https://storage.googleapis.com/vinhomes-data-02/styles/images_263_x_146/public/2024_03/vy pr13_1711443201.jpeg?itok=qLtzVwVM",
      title:
        "Có gì tại Thành phố đảo Hoàng Gia Vinhomes Royal Island vừa ra mắt?",
      content: `<p>Ngay khi ra mắt tr&ecirc;n nền tảng Vinhomes Market, Th&agrave;nh phố đảo Ho&agrave;ng Gia Vinhomes Royal Island (Hải Ph&ograve;ng) đ&atilde; g&acirc;y ấn tượng bởi ch&iacute;nh s&aacute;ch b&aacute;n h&agrave;ng &quot;độc - lạ&quot; c&ugrave;ng sức h&uacute;t từ kh&ocirc;ng gian sống v&agrave; cơ hội &ldquo;v&agrave;ng r&ograve;ng&rdquo; với giới đầu tư.</p>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;">
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><strong><strong>Mua đ&uacute;ng gi&aacute; - cơ hội v&agrave;ng chạm tay si&ecirc;u phẩm</strong></strong></p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Ng&agrave;y 21/3, nền tảng Vinhomes Market của Vinhomes chứng kiến lượng truy cập tăng vọt khi &quot;si&ecirc;u phẩm&quot; Vinhomes Royal Island ch&iacute;nh thức ra mắt với c&aacute;c th&ocirc;ng tin về gi&aacute; v&agrave; ch&iacute;nh s&aacute;ch b&aacute;n h&agrave;ng &quot;độc-lạ&quot; lần đầu được c&ocirc;ng bố.&nbsp;</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Kh&aacute;ch h&agrave;ng v&agrave; nh&agrave; đầu tư c&oacute; thể t&igrave;m hiểu &quot;từ A-Z&quot; về c&aacute;c bất động sản m&igrave;nh quan t&acirc;m tại dự &aacute;n đang &ldquo;g&acirc;y b&atilde;o&rdquo; thị trường chỉ bằng v&agrave;i c&uacute; click chuột.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Nền tảng b&aacute;n h&agrave;ng mới v&agrave; ch&iacute;nh s&aacute;ch đột ph&aacute; m&agrave; Vinhomes &aacute;p dụng cho Th&agrave;nh phố đảo Ho&agrave;ng Gia gi&uacute;p kh&aacute;ch h&agrave;ng được mua đ&uacute;ng gi&aacute; do chủ đầu tư c&ocirc;ng bố ở từng thời điểm (sản phẩm sơ cấp). Đối với trường hợp c&oacute; từ 2 kh&aacute;ch h&agrave;ng trở l&ecirc;n c&ugrave;ng c&oacute; nguyện vọng mua một sản phẩm bất động sản, Vinhomes sẽ tổ chức việc cho trả gi&aacute; c&ocirc;ng khai để minh bạch gi&aacute; trị mua b&aacute;n.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">&quot;C&aacute;ch l&agrave;m mới của Vinhomes kh&ocirc;ng chỉ gi&uacute;p minh bạch h&oacute;a c&aacute;c giao dịch m&agrave; c&ograve;n đảm bảo quyền lợi cũng như tạo cơ hội tiếp cận sản phẩm một c&aacute;ch b&igrave;nh đẳng cho kh&aacute;ch h&agrave;ng v&agrave; nh&agrave; đầu tư ch&uacute;ng t&ocirc;i,&quot; anh Trần Thế Dũng, một nh&agrave; đầu tư l&acirc;u năm tại H&agrave; Nội, nhận định v&agrave; cho biết đang lựa chọn giỏ h&agrave;ng để &quot;xuống tiền&quot; tại dự &aacute;n được đ&aacute;nh gi&aacute; đẳng cấp nhất thị trường hiện tại.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Ngo&agrave;i việc nền tảng Vinhomes Market gi&uacute;p x&oacute;a bỏ mọi giới hạn để việc giao dịch bất động sản trở n&ecirc;n dễ d&agrave;ng, an to&agrave;n v&agrave; tiện lợi hơn ở bất cứ đ&acirc;u, bất cứ l&uacute;c n&agrave;o, kh&aacute;ch h&agrave;ng quan t&acirc;m tới Vinhomes Royal Island c&ograve;n được hỗ trợ đắc lực bởi hai &quot;c&aacute;nh qu&acirc;n&quot; l&agrave; lực lượng tự doanh của Vinhomes v&agrave; c&aacute;c đại l&yacute; h&ugrave;ng hậu.</p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;"><img alt="Với sự đa dạng của các kênh tư vấn, phân phối, khách hàng và nhà đầu tư sẽ dễ dàng lựa chọn được sản phẩm phù hợp tại Vinhomes Royal Island với đúng giá chủ đầu tư công bố." height="428" src="https://photo-mekongasean.epicdn.me/w765/Uploaded/2024/cqdhmdxwp/2024_03_22/thumbnail-1-1-8429.jpg" title="Với sự đa dạng của các kênh tư vấn, phân phối, khách hàng và nhà đầu tư sẽ dễ dàng lựa chọn được sản phẩm phù hợp tại Vinhomes Royal Island với đúng giá chủ đầu tư công bố." width="765" style="border: 0px;"></p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;">Với sự đa dạng của c&aacute;c k&ecirc;nh tư vấn, ph&acirc;n phối, kh&aacute;ch h&agrave;ng v&agrave; nh&agrave; đầu tư sẽ dễ d&agrave;ng lựa chọn được sản phẩm ph&ugrave; hợp tại Vinhomes Royal Island với đ&uacute;ng gi&aacute; chủ đầu tư c&ocirc;ng bố.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Trước đ&oacute;, Vinhomes Royal Island đ&atilde; phả hơi n&oacute;ng l&ecirc;n thị trường bất động sản nhờ m&ocirc; h&igrave;nh &quot;đảo tỷ ph&uacute;&quot; giữa l&ograve;ng phố thị độc nhất v&ocirc; nhị tại Việt Nam.&nbsp;</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Tại đ&acirc;y, cư d&acirc;n sẽ được thụ hưởng những &quot;đặc quyền thượng lưu&quot; như bến du thuyền cao cấp quy m&ocirc; gần 10ha; s&acirc;n golf 36 hố 160ha h&agrave;ng đầu Đ&ocirc;ng Nam &Aacute;; Học viện cưỡi ngựa Ho&agrave;ng Gia; phố đi bộ b&ecirc;n s&ocirc;ng d&agrave;i v&agrave; đẹp nhất Việt Nam; c&ocirc;ng vi&ecirc;n vui chơi giải tr&iacute; gia đ&igrave;nh VinWonders Royal Park với vườn th&uacute; mở Safari&hellip;</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Đặc biệt, Vinhomes Royal Island l&agrave; dự &aacute;n đ&ocirc; thị ở hiếm hoi c&oacute; đa số tư gia sở hữu b&atilde;i tắm nước biển ri&ecirc;ng ngay sau nh&agrave;, mang đến trải nghiệm sống nghỉ dưỡng đ&iacute;ch thực 365 ng&agrave;y/năm.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><strong><strong>Đẳng cấp vượt trội, cơ hội &ldquo;v&agrave;ng mười&rdquo;</strong></strong></p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Sở hữu &quot;bộ sưu tập&quot; phong c&aacute;ch sống đẳng cấp thượng lưu, Th&agrave;nh phố đảo Ho&agrave;ng Gia được chia th&agrave;nh 11 ph&acirc;n khu, bao quanh s&acirc;n golf v&agrave; xen kẽ giữa c&aacute;c hệ thống tiện &iacute;ch v&agrave; dịch vụ, gồm Đảo Vua, Ho&agrave;ng Gia, Qu&yacute; Tộc, Golf Land, Đảo Thi&ecirc;n Đường, Miyabi, Komorebi, Ho&agrave;ng Th&agrave;nh, T&agrave;i Lộc, Kinh Đ&ocirc;, Royal Riverside, với c&aacute;c loại h&igrave;nh nh&agrave; ở đa dạng như biệt thự, liền kề, shophouse&hellip;</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">L&agrave; người y&ecirc;u th&iacute;ch phong c&aacute;ch sống Nhật Bản, chị L&ecirc; Th&uacute;y An (Hải Ph&ograve;ng) d&agrave;nh nhiều thời gian để t&igrave;m hiểu về ph&acirc;n khu Miyabi - sản phẩm đ&aacute;nh dấu sự bắt tay của Vinhomes &amp; Nomura Nhật Bản tại dự &aacute;n Vinhomes Royal Island.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Mang trong m&igrave;nh tinh hoa v&agrave; nghệ thuật của xứ sở mặt trời mọc, ph&acirc;n khu Miyabi l&agrave; sự kết hợp ho&agrave;n hảo giữa địa thế độc đ&aacute;o của đảo thượng lưu c&ugrave;ng tinh hoa thiết kế Nhật Bản, lần đầu xuất hiện tại Việt Nam.&nbsp;</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Đ&aacute;ng ch&uacute; &yacute;, Miyabi l&agrave; ph&acirc;n khu đ&oacute;ng đầu ti&ecirc;n sở hữu b&atilde;i tắm nước biển ri&ecirc;ng sau nh&agrave;, kết hợp với với những căn biệt thự vừa truyền thống pha lẫn hiện đại phong c&aacute;ch Nhật Bản, tạo n&ecirc;n bức tranh sơn thủy hữu t&igrave;nh hiếm c&oacute;.</p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;"><img alt="Miyabi là phân khu chuẩn Nhật với lối kiến trúc riêng biệt tại Vinhomes Royal Island." height="430" src="https://photo-mekongasean.epicdn.me/w765/Uploaded/2024/cqdhmdxwp/2024_03_22/thumbnail-2-1-3886.jpg" title="Miyabi là phân khu chuẩn Nhật với lối kiến trúc riêng biệt tại Vinhomes Royal Island." width="765" style="border: 0px;"></p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;">Miyabi l&agrave; ph&acirc;n khu chuẩn Nhật với lối kiến tr&uacute;c ri&ecirc;ng biệt tại Vinhomes Royal Island.</p>
</div>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;"><br></div>`,
    },
    {
      id: "vinhomes-royal-island-cong-khai-gia-ben-tren-website",
      img: `https://storage.googleapis.com/vinhomes-data-02/styles/images_263_x_146/public/2024_03/VY%20pr12_1711443028.jpeg?itok=cuhtzD7w`,
      title: "Vinhomes Royal Island công khai giá bán trên website",
      content: `<h2 style="text-align: justify;color: rgb(47, 47, 47);background-color: rgb(255, 255, 255);font-size: 16px;">Dự &aacute;n Th&agrave;nh phố Đảo Ho&agrave;ng Gia được ni&ecirc;m yết gi&aacute; c&ocirc;ng khai tr&ecirc;n website Vinhomes Market từ 21/3 để phục vụ nh&agrave; đầu tư t&igrave;m hiểu, tra cứu th&ocirc;ng tin.</h2>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;">
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Người mua, nh&agrave; đầu tư c&oacute; thể t&igrave;m hiểu v&agrave; tra cứu to&agrave;n bộ th&ocirc;ng tin dự &aacute;n, gi&aacute; từng m&atilde; sản phẩm c&ugrave;ng ch&iacute;nh s&aacute;ch tr&ecirc;n website <a href="https://market.vinhomes.vn/" rel="nofollow" target="_blank" style="color: transparent;">Vinhomes Market</a>. C&aacute;c chuy&ecirc;n vi&ecirc;n kinh doanh v&agrave; đại l&yacute; ph&acirc;n phối ch&iacute;nh thức của Vinhomes sẽ hỗ trợ người mua khi c&oacute; nhu cầu.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Chủ đầu tư cho biết động th&aacute;i n&agrave;y thể hiện sự cam kết với người mua sản phẩm do Vinhomes ph&acirc;n phối. Trong đ&oacute;, cư d&acirc;n, nh&agrave; đầu tư được mua đ&uacute;ng gi&aacute; do chủ đầu tư c&ocirc;ng bố ở từng thời điểm (sản phẩm sơ cấp). Đối với trường hợp c&oacute; từ hai người trở l&ecirc;n c&ugrave;ng c&oacute; nguyện vọng mua một sản phẩm, Vinhomes sẽ tổ chức việc cho trả gi&aacute; c&ocirc;ng khai để minh bạch gi&aacute; trị mua b&aacute;n.</p>
    <article>
        <p style="color: rgb(34, 34, 34);font-size: 13px;">Theo chủ đầu tư, việc ni&ecirc;m yết c&ocirc;ng khai gi&aacute; c&ugrave;ng ch&iacute;nh s&aacute;ch b&aacute;n h&agrave;ng tr&ecirc;n website sẽ tạo ra tiền lệ tốt g&oacute;p phần th&uacute;c đẩy m&ocirc;i trường minh bạch v&agrave; sự ph&aacute;t triển l&agrave;nh mạnh cho thị trường bất động sản Việt Nam.</p>
        <figure itemprop="associatedMedia image">
            <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;"><img alt="Phối cảnh Vinhomes Royal Island nhìn từ trên cao. Ảnh: Vinhomes" itemprop="contentUrl" src="https://i1-vnexpress.vnecdn.net/2024/03/21/A1-5-8375-1711017523.jpg?w=680&h=0&q=100&dpr=1&fit=crop&s=7MjP3BpxqE-SmXv1Ikwg-g" style="border: 0px;">Phối cảnh Vinhomes Royal Island nh&igrave;n từ tr&ecirc;n cao.</p>
        </figure>
        <p style="color: rgb(34, 34, 34);font-size: 13px;">Cam kết n&agrave;y được Vinhomes &aacute;p dụng ngay với dự &aacute;n Th&agrave;nh phố Đảo Ho&agrave;ng gia Vinhomes Royal Island mới ra mắt ng&agrave;y 15/3. Vinhomes Royal Island c&oacute; quy m&ocirc; 877 ha, tọa lạc trọn vẹn tr&ecirc;n đảo Vũ Y&ecirc;n, kết nối nội đ&ocirc; hiện tại của Hải Ph&ograve;ng với trung t&acirc;m h&agrave;nh ch&iacute;nh mới Thủy Nguy&ecirc;n. Vị tr&iacute; cho ph&eacute;p dự &aacute;n tiếp cận tới c&aacute;c khu vực trong tam gi&aacute;c kinh tế trọng điểm ph&iacute;a Bắc l&agrave; H&agrave; Nội - Hải Ph&ograve;ng - Quảng Ninh v&agrave; c&aacute;c địa phương kh&aacute;c th&ocirc;ng qua hệ thống đường thủy, bộ, h&agrave;ng kh&ocirc;ng.</p>
        <p style="color: rgb(34, 34, 34);font-size: 13px;">Dự &aacute;n chia th&agrave;nh 11 ph&acirc;n khu, bao quanh s&acirc;n golf ở trung t&acirc;m v&agrave; xen kẽ giữa c&aacute;c hệ thống tiện &iacute;ch dịch vụ. Vinhomes Royal Island bao gồm c&aacute;c loại h&igrave;nh nh&agrave; ở như biệt thự, liền kề, shophouse...Cư d&acirc;n được hưởng những đặc quyền thượng lưu như: bến du thuyền cao cấp quy m&ocirc; gần 10 ha; s&acirc;n golf 36 hố 160 ha; học viện cưỡi ngựa Ho&agrave;ng Gia; phố đi bộ b&ecirc;n s&ocirc;ng; c&ocirc;ng vi&ecirc;n vui chơi giải tr&iacute; gia đ&igrave;nh VinWonders Royal Park,... Đa số c&aacute;c sản phẩm nh&agrave; tại Vinhomes Royal Island sở hữu b&atilde;i tắm nước biển ri&ecirc;ng ngay sau nh&agrave;.</p>
        <figure itemprop="associatedMedia image">
            <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;"><img alt="Một góc dự án với bến du thuyền. Ảnh: Vinhomes" itemprop="contentUrl" src="https://i1-vnexpress.vnecdn.net/2024/03/21/thumbnail-A4-7764-1711017523.jpg?w=680&h=0&q=100&dpr=1&fit=crop&s=ZQWcH1RwKzt8tH26Kl70iw" style="border: 0px;">&nbsp;Một g&oacute;c dự &aacute;n với bến du thuyền.</p>
        </figure>
        <p style="color: rgb(34, 34, 34);font-size: 13px;">Cư d&acirc;n c&ograve;n được sử dụng c&aacute;c tiện &iacute;ch chăm s&oacute;c sức khoẻ tại Ph&ograve;ng kh&aacute;m đa khoa Quốc tế Vinmec với đặc quyền &quot;y tế tận nh&agrave;&quot;. Trẻ em được học tại 7 trường Vinschool v&agrave; trường quốc tế H&agrave;n Quốc. Ngo&agrave;i ra, cư d&acirc;n c&ograve;n được nghĩ dưỡng với hệ thống 31 c&ocirc;ng vi&ecirc;n, 10 bể bơi trong nh&agrave; v&agrave; ngo&agrave;i trời, tổ hợp s&acirc;n tennis, s&acirc;n cầu l&ocirc;ng, b&oacute;ng đ&aacute;, b&oacute;ng chuyền, c&aacute;c vườn tập dưỡng sinh, gym... bao phủ khắp dự &aacute;n. An ninh tại Vinhomes Royal Island sử dụng hệ thống c&ocirc;ng nghệ t&iacute;ch hợp AI c&ugrave;ng t&agrave;u tuần tra tr&ecirc;n s&ocirc;ng v&agrave; dịch vụ quản l&yacute; 5 sao để đảm bảo sự ri&ecirc;ng tư, an to&agrave;n.</p>
    </article>
</div>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;"><br></div>`,
    },
    {
      id: "kham-pha-vien-kim-cuong-tren-vuong-mien-tai-dao-ty-phu-vinhomes-royal-island",
      img: "https://storage.googleapis.com/vinhomes-data-02/styles/images_263_x_146/public/2024_03/VY%20PR11_1711442745.jpeg?itok=EtMnwryD",
      title: `Khám phá “viên kim cương trên vương miện” tại “đảo tỷ phú” Vinhomes Royal Island`,
      content: `<p>Trong bộ sưu tập những tiện &iacute;ch đẳng cấp thế giới quy tụ tại &ldquo;đảo tỷ ph&uacute;&rdquo; Vinhomes Royal Island (Vũ Y&ecirc;n, Hải Ph&ograve;ng), kh&ocirc;ng thể kh&ocirc;ng nhắc đến River Walk - phố đi bộ văn h&oacute;a, vui chơi, mua sắm, ẩm thực bờ s&ocirc;ng d&agrave;i v&agrave; đẹp nhất Việt Nam.</p>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;">
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><strong><strong>&ldquo;Vi&ecirc;n kim cương tr&ecirc;n vương miện&rdquo; của c&aacute;c BĐS si&ecirc;u sang</strong></strong></p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Đại lộ Ng&ocirc;i sao - phố đi bộ nằm dọc bờ s&ocirc;ng Tsim Sha Tsui (Hongkong) từ l&acirc;u đ&atilde; trở th&agrave;nh một trong những điểm đến văn h&oacute;a hấp dẫn nhất, kh&ocirc;ng chỉ cho người d&acirc;n xứ Cảng thơm, m&agrave; c&ograve;n của du kh&aacute;ch quốc tế. Đ&acirc;y l&agrave; địa điểm thường được c&aacute;c thương hiệu lớn nhất thế giới chọn l&agrave;m nơi ra mắt c&aacute;c bộ sưu tập mới, l&agrave; s&agrave;n diễn quen thuộc của những ng&ocirc;i sao hạng nhất trong l&agrave;ng điện ảnh v&agrave; thời trang quốc tế. V&agrave;o l&uacute;c 20h h&agrave;ng ng&agrave;y, từ phố đi bộ n&agrave;y, du kh&aacute;ch sẽ được m&atilde;n nh&atilde;n với m&agrave;n tr&igrave;nh diễn miễn ph&iacute; &ldquo;bản giao hưởng &acirc;m thanh, &aacute;nh s&aacute;ng&rdquo; k&eacute;o d&agrave;i 15 ph&uacute;t, trong đ&oacute; 44 t&ograve;a nh&agrave; cao chọc trời ở cả hai b&ecirc;n cảng Victoria được thắp s&aacute;ng bằng m&agrave;n h&igrave;nh hiển thị đa phương tiện c&ugrave;ng đ&egrave;n laser v&agrave; &acirc;m nhạc.</p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;"><img alt="" src="https://media.baodautu.vn/Images/phuongthanh/2024/03/21/H1%20(1).jpg" style="border: 0px;"></p>
    <p style="text-align: center;color: rgb(34, 34, 34);font-size: 13px;">Phố đi bộ ven biển Ng&ocirc;i Sao - điểm đến nổi tiếng của xứ Cảng Thơm thu h&uacute;t h&agrave;ng triệu người đến thăm, với gi&aacute; trị BĐS l&ecirc;n tới h&agrave;ng chục ngh&igrave;n đ&ocirc; la cho một m&eacute;t vu&ocirc;ng.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Những sự kiện, hoạt động tại đ&acirc;y đ&atilde; đ&oacute;ng g&oacute;p lớn cho nền <a href="https://baodautu.vn/thoi-su-d1/" style="color: transparent;">kinh tế</a> Hongkong bằng c&aacute;ch tạo ra doanh thu đột ph&aacute; th&ocirc;ng qua lượng kh&aacute;ch khổng lồ đặt ph&ograve;ng kh&aacute;ch sạn, ăn uống v&agrave; chi ti&ecirc;u mua sắm&hellip; C&aacute;c lợi thế tr&ecirc;n g&oacute;p phần đưa BĐS quanh phố đi bộ Ng&ocirc;i sao v&agrave;o top đắt nhất Hongkong v&agrave; thế giới (khoảng 45.000 USD/m2, tương đương khoảng 1,4 tỷ đồng/m2). &nbsp;</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Ngo&agrave;i Đại lộ Ng&ocirc;i sao, những c&aacute;i t&ecirc;n như Garosu-gil (Seoul, H&agrave;n Quốc) hay Ginza (Tokyo, Nhật Bản) đều l&agrave; minh chứng cho tiềm năng v&ocirc; hạn của c&aacute;c tuyến phố đi bộ. Được v&iacute; như &ldquo;vi&ecirc;n kim cương tr&ecirc;n vương miện&rdquo;, đ&acirc;y kh&ocirc;ng chỉ l&agrave; điểm đến an to&agrave;n, hiện đại, trung t&acirc;m mua sắm v&agrave; khu vui chơi giải tr&iacute; lớn thu h&uacute;t h&agrave;ng triệu du kh&aacute;ch m&agrave; c&ograve;n l&agrave; yếu tố then chốt tạo n&ecirc;n những khu vực BĐS đắt đỏ.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Tới đ&acirc;y, River Walk, phố đi bộ văn h&oacute;a, vui chơi, mua sắm, ẩm thực bờ s&ocirc;ng d&agrave;i v&agrave; đẹp nhất Việt Nam tại &ldquo;đảo tỷ ph&uacute;&rdquo; Vinhomes Royal Island sẽ ghi t&ecirc;n m&igrave;nh v&agrave;o danh s&aacute;ch &ldquo;si&ecirc;u điểm đến&rdquo; quốc tế n&agrave;y. Kế cận phố đi bộ ven s&ocirc;ng ch&iacute;nh l&agrave; ph&acirc;n khu T&agrave;i Lộc, bao gồm những d&atilde;y shophouse được thiết kế sang trọng, đẳng cấp. Vị tr&iacute; đắc địa sẽ khiến ph&acirc;n khu T&agrave;i Lộc n&oacute;i chung v&agrave; phố đi bộ n&oacute;i ri&ecirc;ng trở th&agrave;nh điểm hẹn mua sắm, ẩm thực, vui chơi giải tr&iacute; mới cho cư d&acirc;n v&agrave; kh&aacute;ch đến <a href="https://baodautu.vn/dau-tu-d2/" style="color: transparent;">dự &aacute;n</a>.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;"><strong><strong>Tiềm năng th&agrave;nh &ldquo;si&ecirc;u điểm đến&rdquo; của phố đi bộ ven s&ocirc;ng d&agrave;i v&agrave; đẹp nhất Việt Nam</strong></strong></p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Được kiến tạo để trở th&agrave;nh &ldquo;đặc khu mới&rdquo; của giới tinh hoa trong nước v&agrave; quốc tế, Vinhomes Royal Island quy tụ hệ thống tiện &iacute;ch v&agrave; dịch vụ đẳng cấp h&agrave;ng đầu thế giới, với những đặc quyền cư d&acirc;n vượt trội, lần đầu ti&ecirc;n xuất hiện tại Việt Nam. Trong đ&oacute;, phố đi bộ văn h&oacute;a, vui chơi, mua sắm, ẩm thực bờ s&ocirc;ng d&agrave;i v&agrave; đẹp nhất Việt Nam được đ&aacute;nh gi&aacute; l&agrave; một trong những si&ecirc;u phẩm với mục ti&ecirc;u đem đến cho cư d&acirc;n v&agrave; du kh&aacute;ch những trải nghiệm độc nhất v&ocirc; nhị.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Nằm song song s&ocirc;ng Cấm với tầm nh&igrave;n view trực diện đ&ocirc; thị Hải Ph&ograve;ng hoa lệ, phố đi bộ ven s&ocirc;ng River Walk sẽ sở hữu những cụm c&ocirc;ng vi&ecirc;n artwork chủ đề đặc sắc, đ&aacute;p ứng nhu cầu của mọi đối tượng cư d&acirc;n v&agrave; du kh&aacute;ch. Trong đ&oacute;, tuyến phố T&igrave;nh y&ecirc;u với đ&agrave;i phun nước nghệ thuật v&agrave; biểu tượng kh&oacute;a t&igrave;nh y&ecirc;u sẽ l&agrave; điểm đến y&ecirc;u th&iacute;ch, nơi c&aacute;c cặp đ&ocirc;i kết lời thề hẹn.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Tuyến phố Trẻ em v&agrave; Gia đ&igrave;nh nổi bật với những quầy h&agrave;ng h&igrave;nh th&ugrave; ngộ nghĩnh như những lon nước khổng lồ, artwork thần ti&ecirc;n cổ t&iacute;ch, c&ugrave;ng những tr&ograve; chơi đặc sắc: v&ograve;ng quay ngựa gỗ carousel, cốc xoay v&agrave; skydrop cảm gi&aacute;c mạnh, nh&agrave; phao, th&uacute; nh&uacute;n... đầy m&agrave;u sắc hấp dẫn trẻ em.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Nơi đ&acirc;y c&ograve;n c&oacute; tuyến phố Hải Ph&ograve;ng &amp; Biển với tượng đồng Chọi tr&acirc;u Đồ Sơn c&ugrave;ng những h&igrave;nh ảnh th&acirc;n quen với phố cảng như mỏ neo, hội đua thuyền, l&iacute;nh hải qu&acirc;n...</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Kh&ocirc;ng chỉ vui chơi qu&ecirc;n lối về, tại River Walk, du kh&aacute;ch c&ograve;n được &ldquo;ăn cả thế giới&rdquo; với c&aacute;c phố chợ ẩm thực đặc sắc: chợ đ&ecirc;m H&agrave;n Quốc/Th&aacute;i Lan, chợ đ&ecirc;m hải sản 3 miền, phố chợ thi&ecirc;n đường ăn vặt Hải Ph&ograve;ng&hellip; Nơi đ&acirc;y hứa hẹn tạo n&ecirc;n điểm đến h&agrave;ng đầu miền Bắc về ẩm thực, văn h&oacute;a, mua sắm.</p>
    <p style="color: rgb(34, 34, 34);font-size: 13px;">Đặc biệt khi về đ&ecirc;m, khung cảnh River Walk sẽ trở n&ecirc;n lung linh với h&agrave;ng ngh&igrave;n hiệu ứng &aacute;nh s&aacute;ng rực rỡ bố tr&iacute; khắp c&aacute;c con phố lẫn quảng trường. Loạt đ&egrave;n lồng treo cao, đ&egrave;n hiệu ứng chiếu t&aacute;n c&acirc;y, th&acirc;n c&acirc;y, tr&igrave;nh diễn c&ocirc;ng nghệ mapping &aacute;nh s&aacute;ng&hellip; sẽ đưa phố đi bộ trở th&agrave;nh một biểu tượng nghệ thuật với c&aacute;c phong c&aacute;ch độc đ&aacute;o c&oacute; 1-0-2 ở th&agrave;nh phố cảng.</p>
</div>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;"><br></div>`,
    },
  ],
};

const params = new Proxy(new URLSearchParams(window.location.search), {
  get: (searchParams, prop) => searchParams.get(prop),
});

let title = params.title;
if (title != "undefined" && title != "" && title != null) {
  for (let news_data of news_datas.data) {
    if (news_data.id == title) {
      let content_container = document.getElementsByClassName(
        "news_detail_content_left"
      )[0];
      let content_heading = content_container.getElementsByTagName("h5")[0];
      content_heading.innerText = news_data.title;
      let content_detail =
        content_container.getElementsByClassName("new_detail_content")[0];
      content_detail.innerHTML = news_data.content;
    }
  }
} else {
  window.location.replace(`http://127.0.0.1:5502/pages/news/tin-tuc.html`);
}
