let location_data = {
  data: [
    {
      id: "01",
      titile: "",
      content: `<h2 style="text-align: justify;color: rgb(47, 47, 47);background-color: rgb(255, 255, 255);font-size: 16px;">Ocean City, Th&agrave;nh phố điểm đến ph&iacute;a Đ&ocirc;ng H&agrave; Nội tự h&agrave;o được International Business Times (IBTimes)&nbsp;&ndash; Một trong những thời b&aacute;o kinh doanh lớn nhất tại Mỹ&nbsp;c&ugrave;ng nhiều thời b&aacute;o danh gi&aacute; tr&ecirc;n thế giới đ&aacute;nh gi&aacute; l&agrave; Nơi đ&aacute;ng sống bậc nhất h&agrave;nh tinh.</h2>
<div style="text-align: justify;color: rgb(119, 119, 119);background-color: rgb(255, 255, 255);font-size: 14px;">
    <p style="text-align: justify;color: rgb(34, 34, 34);font-size: 13px;"><span style="font-size: 12pt;"><span style="font-size: 11pt;"><span style="color: black;">Trải qua h&agrave;nh tr&igrave;nh hơn 5 năm h&igrave;nh th&agrave;nh &amp; ph&aacute;t triển, Ocean City đ&atilde; trở th&agrave;nh <strong><strong>điểm đến hấp dẫn cho c&aacute;c c&ocirc;ng d&acirc;n to&agrave;n cầu</strong></strong></span></span><strong><strong><span style="font-size: 11pt;"><span style="color: black;">&nbsp;sống kết nối, ho&agrave; m&igrave;nh v&agrave;o sự ph&aacute;t triển, đề cao gi&aacute; trị sức khoẻ, tinh thần v&agrave; cộng đồng</span></span></strong></strong><span style="font-size: 11pt;"><span style="color: black;">. Nơi đ&acirc;y hiện</span></span> <span style="font-size: 11pt;"><span style="color: black;">l&agrave; ng&ocirc;i nh&agrave; của hơn <strong><strong>60.000 cư d&acirc;n, gồm cả cư d&acirc;n Việt Nam v&agrave; quốc tế</strong></strong>. Trong đ&oacute;, <strong><strong>cộng đồng cư d&acirc;n H&agrave;n Quốc đang</strong></strong></span></span><strong><strong>&nbsp;</strong></strong><strong><strong><span style="font-size: 11pt;"><span style="color: black;">chiếm số lượng đ&ocirc;ng đảo nhất</span></span></strong></strong><strong><strong>&nbsp;</strong></strong><span style="font-size: 11pt;"><span style="color: black;">trong cộng đồng&nbsp;</span></span><span style="font-size: 11pt;"><span style="color: black;">cư</span></span><span style="font-size: 11pt;"><span style="color: black;">&nbsp;d&acirc;n quốc tế. Đ&oacute; l&agrave; t&iacute;n hiệu đ&aacute;ng mừng cho thấy Ocean City được cộng đồng cư d&acirc;n H&agrave;n Quốc tại Việt Nam đ&oacute;n nhận rất t&iacute;ch cực.</span></span></span></p>
    <p style="text-align: justify;color: rgb(34, 34, 34);font-size: 13px;">&nbsp;</p>
    <p style="text-align: justify;color: rgb(34, 34, 34);font-size: 13px;"><span style="font-size: 12pt;"><span style="font-size: 11pt;"><span style="color: black;">Đ&aacute;p lại sự tin y&ecirc;u của cộng đồng H&agrave;n Quốc, trong thời gian qua, Ocean City lu&ocirc;n <strong><strong>đầu tư mạnh mẽ v&agrave;o h&agrave;ng loạt c&aacute;c dịch vụ, tiện &iacute;ch cũng như ch&iacute;nh s&aacute;ch ưu đ&atilde;i d&agrave;nh ri&ecirc;ng cho cư d&acirc;n/kh&aacute;ch h&agrave;ng H&agrave;n Quốc</strong></strong> nhằm mục ti&ecirc;u thu h&uacute;t v&agrave; ph&aacute;t triển cộng đồng H&agrave;n Quốc tại Ocean City.</span></span></span></p>
    <p style="text-align: justify;color: rgb(34, 34, 34);font-size: 13px;"><img src="https://storage.googleapis.com/vinhomes-data-02/styles/images_160_x_120/public/2022_10/1303_Anh_1_1666754093.jpeg?itok=KisV6NIx" alt=""><br></p>
</div>`,
    },
  ],
};
